---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-vpn
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "multus-vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eno1.770",
          "mode": "bridge",
          "capabilities": { "ips": true, "mac": true },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/5", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "8.0.0.0/7", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "11.0.0.0/8", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "12.0.0.0/6", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "16.0.0.0/4", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "32.0.0.0/3", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "64.0.0.0/3", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "96.0.0.0/6", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "100.0.0.0/10", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "100.128.0.0/9", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "101.0.0.0/8", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "102.0.0.0/7", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "104.0.0.0/5", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "112.0.0.0/4", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "128.0.0.0/3", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "160.0.0.0/5", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "168.0.0.0/6", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "172.0.0.0/12", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "172.32.0.0/11", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "172.64.0.0/10", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "172.128.0.0/9", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "173.0.0.0/8", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "174.0.0.0/7", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "176.0.0.0/4", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.0.0.0/9", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.128.0.0/11", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.160.0.0/13", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.169.0.0/16", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.170.0.0/15", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.172.0.0/14", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.176.0.0/12", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "192.192.0.0/10", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "193.0.0.0/8", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "194.0.0.0/7", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "196.0.0.0/6", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "200.0.0.0/5", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "208.0.0.0/4", "gw": "10.77.0.1", "priority": 1 },
              { "dst": "240.0.0.0/4", "gw": "10.77.0.1", "priority": 1 }
            ]
          }
        }
      ]
    }
