---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: actions-runner-controller
      namespace: actions-runner-system
  interval: 1h
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: actions-runner-system
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller-runners
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller
  dependsOn:
    - name: actions-runner-controller
    - name: openebs
      namespace: openebs
  interval: 1h
  path: "./kubernetes/apps/actions-runner-system/actions-runner-controller/runners"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: actions-runner-system
  wait: false
