---
services:
  node-exporter:
    command:
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
      - --web.listen-address=0.0.0.0:9100
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.10.2
    network_mode: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /:/host/root:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  smartctl-exporter:
    container_name: smartctl-exporter
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    ports:
      - 9633:9633
    privileged: true
    restart: unless-stopped
    user: root

  nut_exporter:
    # renovate: datasource=docker depName=ghcr.io/druggeri/nut_exporter
    image: ghcr.io/druggeri/nut_exporter:3.2.3
    container_name: nut_exporter
    restart: unless-stopped
    command:
      - '--nut.server=10.0.1.10'
      - '--log.level=debug'
      - '--nut.vars_enable=battery.charge,battery.runtime,ups.status,ups,input.voltage,battery.voltage'
    network_mode: "host"

