---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bazarr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: bazarr
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./kubernetes/apps/downloads/bazarr/app"
  postBuild:
    substitute:
      APP: bazarr
      VOLSYNC_CLAIM: bazarr-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
